# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagboot', '0009_websitesettings_container_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='container_class',
            field=models.CharField(choices=[('container', 'container - fixed width'), ('container-fluid', 'container-fluid - full width')], default='container', max_length=42),
        ),
    ]
